name: hugo build from source

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: get hugo
        run: sudo snap install hugo

      - name: build
        run: hugo
